# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_OPTS: '-Dmaven.test.failure.ignore=false' # Fail the build on test failures
  JAVA_HOME: '/usr/lib/jvm/java-11-openjdk-amd64'
steps:
  # Step 1: Check out the repository
  - checkout: self

  # Step 2: Install Maven dependencies and run tests
  - script: |
      mvn clean install -B -DskipTests=false
    displayName: 'Build and Run Tests with Maven'

  # Step 3: Publish Test Results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'  # Path to TestNG test reports
      testRunTitle: 'TestNG API Test Results'  # Display title in Azure DevOps
      mergeTestResults: true

  # Step 4 (Optional): Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/target'  # Maven build output directory
      artifactName: 'drop'  # Name for the artifact
      publishLocation: 'Container'  # Store artifacts within Azure DevOps